include:
  - ./reverie-web/docker-compose.reverie-web.yml
  - path: ./postgres/docker-compose.postgres.yml
    env: ./.env

services:
  nginx:
    image: ghcr.io/blazingneutron/reverie-nginx
    build:
      context: nginx/
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"