name: Build Docker Images

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build_images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and push images
    env:
      VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build migrator image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./docker/migrator/
          file: ./docker/migrator/Dockerfile
          build-contexts: |
            migrations=./supabase/migrations
          tags: ghcr.io/blazingneutron/reverie-migrator:${{ github.sha }},ghcr.io/blazingneutron/reverie-migrator:latest
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
      - name: Build reverie-web image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          tags: ghcr.io/blazingneutron/reverie-web:${{ github.sha }},ghcr.io/blazingneutron/reverie-web:latest
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
      - name: Build nginx image
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./docker/nginx
          file: ./docker/nginx/Dockerfile
          tags: ghcr.io/blazingneutron/reverie-nginx:${{ github.sha }},ghcr.io/blazingneutron/reverie-nginx:latest
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline